### ISSUE TITLE
Myballがふたつになった

### ISSUE THREAD

**Issue by muff1225** [ukyoda/seradama#6]
一回ブラウザ開いて、ちょっぴり回線が切れて再接続されたときに自分のボール（青）が二つになった。操作はひとつだけしかできず。

**Comment by muff1225** [comment]
原因はよくわからん

**Comment by miyagikenta** [comment]
再接続して新しいセッションIDが払い出されると、ボールも新しく追加されるけど、以前のボールの色は変わらないので、自分のボールが2個あるように見える。
まずは、切断したときとタイムアウトしたときの処理を入れないとダメですね。

**Comment by muff1225** [comment]
回答ありがとう。
タイムアウトの判定はNode.js側(@miyagikenta)、
ボール削除はクライアント側(@ukyoda)ですね

**Comment by muff1225** [comment]
セッション切れに対応しているのでクローズ
