### ISSUE TITLE
SurfaceとAndroidのブラウザで加速度が逆転してる

### ISSUE THREAD

**Issue by muff1225** [ukyoda/seradama#7]
上に傾けると下にいくし、
左に傾けると右にいく。

@ukyoda 
@miyagikenta 
どういうことや！！！

**Comment by miyagikenta** [comment]
iPhoneとAndroidではセンサの値の正負が逆になるみたいですね。

**Comment by miyagikenta** [comment]
クライアント側にこの処理を入れればいいのかな？

```
if (navigator.userAgent.indexOf('Android') > 0) {
    x *= -1;
}
```

**Comment by muff1225** [comment]
うん、多分それでいいと思うけど、iOSだけが違う気もするんだよな～
@ukyodaさん、対応よろしくお願いします！！！

**Comment by miyagikenta** [comment]
iOSが正しくて他の端末が間違ってるだけなので大丈夫です。

**Comment by muff1225** [comment]
残念ながら世の中はそうは思っていないようです残念です実に残念です・・・
http://www.businessinsider.com/iphone-v-android-market-share-2014-5

**Comment by ukyoda** [comment]
iOSとAndroidで軸向きを変えるメソッドを追加しましたー。

私が持っているiPhoneとGalaxy Nexusでとりあえずうまく動いていたので
多分問題ないかと。。。

ちなみにそれ以外の端末はわからんので

**Comment by filderschoice** [comment]
最新のgitの内容で動作確認してみました。
Androidは問題なく動きましたが、Surfaceだと軸向きが逆になるっぽいですね。
センサの類は端末依存がデカそうなので、とりあえずiPhoneとAndroidで動けばおｋということにしますか？
あとはできればNexusのタブレットとiPadの動確も確認しておきたいところですが。

# Nexusタブは宮城さん、iPadは片山にお願いしたいところです。

2014年6月3日 0:54 ukyoda notifications@github.com:

**Comment by muff1225** [comment]
iPadはUA別っすね。今Otherの方に入ってるはず。
Androidタブレットは今のロジックでオッケー　:)

●iOS6
Mozilla/5.0 (iPad; CPU OS 6_0 like Mac OS X) AppleWebKit/536.26 (KHTML, like Gecko) Version/6.0 Mobile/10A403 Safari/8536.25

**Comment by ukyoda** [comment]
iPad対応しましたー！！

**Comment by muff1225** [comment]
Surfaceがやっぱ逆っす
Win機全部そうなのかな？
土曜日、ビックカメラで確かめてみよう

**Comment by muff1225** [comment]
Surfaceいけてるんでこれはクローズします
