### ISSUE TITLE
さくらサーバの方は接続数2以上で急激に遅くなるね

### ISSUE THREAD

**Issue by miyagikenta** [ukyoda/seradama#8]
さくらサーバの方はクライアント接続数1個のときは快適に動くんだけど、接続数2個以上にすると急激にカクカクしだしますね。
cloud9の方は接続数増やしてもあまり変化なし。

**Comment by muff1225** [comment]
facebookでコンソールのURLを送りました。
モニタリングできるので解析に使ってください。

見た感じさくらだからってことはなさそうな感じ。
センサーのインプットが多いのがわかる。

**Comment by muff1225** [comment]
お試しアカウントで速度制限かかっていたということで、これはクローズで。
